// Generated by gencpp from file swarmie_msgs/Waypoint.msg
// DO NOT EDIT!


#ifndef SWARMIE_MSGS_MESSAGE_WAYPOINT_H
#define SWARMIE_MSGS_MESSAGE_WAYPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarmie_msgs
{
template <class ContainerAllocator>
struct Waypoint_
{
  typedef Waypoint_<ContainerAllocator> Type;

  Waypoint_()
    : action(0)
    , id(0)
    , x(0.0)
    , y(0.0)  {
    }
  Waypoint_(const ContainerAllocator& _alloc)
    : action(0)
    , id(0)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _action_type;
  _action_type action;

   typedef uint32_t _id_type;
  _id_type id;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;


    enum { ACTION_ADD = 0u };
     enum { ACTION_REMOVE = 1u };
     enum { ACTION_REACHED = 2u };
 

  typedef boost::shared_ptr< ::swarmie_msgs::Waypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarmie_msgs::Waypoint_<ContainerAllocator> const> ConstPtr;

}; // struct Waypoint_

typedef ::swarmie_msgs::Waypoint_<std::allocator<void> > Waypoint;

typedef boost::shared_ptr< ::swarmie_msgs::Waypoint > WaypointPtr;
typedef boost::shared_ptr< ::swarmie_msgs::Waypoint const> WaypointConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarmie_msgs::Waypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarmie_msgs::Waypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace swarmie_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'swarmie_msgs': ['/home/timeinvestor2/SwarmBaseCode-ROS/src/swarmie_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::swarmie_msgs::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarmie_msgs::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarmie_msgs::Waypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarmie_msgs::Waypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarmie_msgs::Waypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarmie_msgs::Waypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarmie_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bca889e1ccc791398deb93b9d6ed5f04";
  }

  static const char* value(const ::swarmie_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbca889e1ccc79139ULL;
  static const uint64_t static_value2 = 0x8deb93b9d6ed5f04ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarmie_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarmie_msgs/Waypoint";
  }

  static const char* value(const ::swarmie_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarmie_msgs::Waypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Defines a labeled point\n\
uint32 ACTION_ADD=0\n\
uint32 ACTION_REMOVE=1\n\
uint32 ACTION_REACHED=2\n\
uint32 action\n\
uint32 id\n\
float32 x\n\
float32 y\n\
";
  }

  static const char* value(const ::swarmie_msgs::Waypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarmie_msgs::Waypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action);
      stream.next(m.id);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Waypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarmie_msgs::Waypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarmie_msgs::Waypoint_<ContainerAllocator>& v)
  {
    s << indent << "action: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.action);
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARMIE_MSGS_MESSAGE_WAYPOINT_H
